CREATE TYPE CONTACT AS OBJECT
(EMAIL VARCHAR2(255),
PHONE_NUMBER NUMBER);

CREATE TABLE USERS
(
ACC_ID VARCHAR2(255) CONSTRAINT USER_ACC_ID_PK PRIMARY KEY,
NAME VARCHAR2(255) , 
CONTACT CONTACT ,
PASSWORD VARCHAR2(255) ,
DEPARTMENT VARCHAR2(255) ,
RESEARCH_INTEREST VARCHAR2(255) ,
NUMBER_OF_RESEARCHES VARCHAR2(255) ,
ATTENDED_CONFERENCE VARCHAR2(255) 
);

CREATE TABLE ADMIN
(
ADMIN_ID VARCHAR2(255) CONSTRAINT ADMIN_ADMIN_ID_PK PRIMARY KEY,
ACC_ID VARCHAR2(255) NOT NULL,
CONSTRAINT ADMIN_ACCOUNT_ID_FK FOREIGN 
KEY(ACC_ID) REFERENCES USERS(ACC_ID) ON DELETE CASCADE ,
ROLE VARCHAR2(255) );

CREATE TABLE FACULTY
(
FACULTY_ID VARCHAR2(255) CONSTRAINT FACULTY_FACULTY_ID_PK PRIMARY KEY,
ACC_ID VARCHAR2(255) NOT NULL,
CONSTRAINT FACULTY_ACCOUNT_ID_FK FOREIGN 
KEY(ACC_ID) REFERENCES USERS(ACC_ID) ON DELETE CASCADE ,
INSTITUTION VARCHAR2(255),
DESIGNATION VARCHAR2(255),
QUALIFICATION VARCHAR2(255) );

CREATE TABLE ALUMNI
(
STUDENT_ID VARCHAR2(255) CONSTRAINT ALUMNI_STUDENT_ID_PK PRIMARY KEY ,
ACC_ID VARCHAR2(255) NOT NULL,
CONSTRAINT ALUMNI_ACCOUNT_ID_FK FOREIGN 
KEY(ACC_ID) REFERENCES USERS(ACC_ID) ON DELETE CASCADE,
CURRENT_JOB VARCHAR2(255) ,
BATCH VARCHAR2(255) ,
ENROLL_YEAR DATE,
GRAD_YEAR DATE,
EXPERIENCES VARCHAR2(255) );

CREATE TABLE STUDENT
(
STUDENT_ID VARCHAR2(255)  CONSTRAINT STUDENT_STUDENT_ID_PK PRIMARY KEY,
ACC_ID VARCHAR2(255)  NOT NULL,
CONSTRAINT STUDENT_ACCOUNT_ID_FK FOREIGN KEY(ACC_ID) REFERENCES USERS(ACC_ID) ON DELETE CASCADE,
INSTITUTION VARCHAR2(255) ,
ENROLL_YEAR DATE,
CGPA VARCHAR2(255) 
);

CREATE TABLE RESEARCH
(
RESEARCH_ID VARCHAR2(255) CONSTRAINT RESEARCH_RESEARCH_ID_PK PRIMARY KEY,
APPROVE_STATUS VARCHAR2(255) ,
PAPER_PDF VARCHAR2(255) , 
PAPER_LINK VARCHAR2(255) ,
PUBLISHER VARCHAR2(255) ,
PAPER_TITLE VARCHAR2(255) ,
PUBLISH_STATUS VARCHAR2(255),
PAPER_ABSTRACT VARCHAR2(500), 
PAPER_TYPE VARCHAR2 (255)
);

CREATE TABLE STUDENT_RESEARCH
(
STUDENT_ID VARCHAR2(255) NOT NULL, 
RESEARCH_ID VARCHAR2(255) NOT NULL,
CONSTRAINT STD_RESEARCH_STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)  ON DELETE CASCADE, 
CONSTRAINT STD_RESEARCH_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
);

CREATE TABLE FACULTY_RESEARCH
(
FACULTY_ID VARCHAR2(255) NOT NULL, 
RESEARCH_ID VARCHAR2(255) NOT NULL,
CONSTRAINT FAC_RESEARCH_FACULTY_ID_FK FOREIGN KEY(FACULTY_ID) REFERENCES FACULTY(FACULTY_ID) ON DELETE CASCADE, 
CONSTRAINT FAC_RESEARCH_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
);

CREATE TABLE ALUMNI_RESEARCH
(
STUDENT_ID VARCHAR2(255) ,
RESEARCH_ID VARCHAR2(255) ,
CONSTRAINT ALM_RESEARCH_STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) REFERENCES ALUMNI(STUDENT_ID) ON DELETE CASCADE, 
CONSTRAINT ALM_RESEARCH_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
);

CREATE TABLE CONSULTS
(
STUDENT_ID VARCHAR2(255) , 
FACULTY_ID VARCHAR2(255) , 
FIELD_OF_RESEARCH VARCHAR2(255) ,
CONSTRAINT CONSULTS_STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE, 
CONSTRAINT CONSULTS_FACULTY_ID_FK FOREIGN KEY(FACULTY_ID) REFERENCES FACULTY(FACULTY_ID) ON DELETE CASCADE
);

CREATE TABLE CONFERENCE_PAPER
(
RESEARCH_ID VARCHAR2(255) ,
CONFERENCE_NAME VARCHAR2(255) ,
TYPE_OF_PAPER VARCHAR2(255) ,
DOI VARCHAR2(255) ,
CONSTRAINT CON_PAPER_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
); 

CREATE TABLE JOURNAL_PAPER
(
RESEARCH_ID VARCHAR2(255) ,
JOURNAL_NAME VARCHAR2(255) ,
SJR_RATING VARCHAR2(255) ,
ISSN VARCHAR2(255) ,
CONSTRAINT JRN_PAPER_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
);

CREATE TABLE RESEARCH_AREA
(
RESEARCH_ID VARCHAR2(255) ,
RESEARCH_AREA VARCHAR2(255), 
CONSTRAINT AREA_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
);

CREATE TABLE AWARDS
(
RESEARCH_ID VARCHAR2(255) NOT NULL,
AWARDS VARCHAR2(255) ,
CONSTRAINT AWARDS_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
);

CREATE TABLE FUND_REQUESTS
(
FUND_ID VARCHAR2(255) CONSTRAINT FUND_REQ_FUND_ID_PK PRIMARY KEY,
AMOUNT_RAISED NUMBER CHECK(AMOUNT_RAISED>=0), 
AMOUNT_REQUIRED NUMBER  CHECK(AMOUNT_REQUIRED>0), 
AMOUNT_LEFT AS (AMOUNT_REQUIRED-AMOUNT_RAISED),
TRUST_ACCNO NUMBER,
BKASH NUMBER,
FUND_STATUS VARCHAR2(255) 
);

CREATE TABLE GRANT_PROVIDER
(
GRANT_PROVIDER_ID VARCHAR2(255) CONSTRAINT GP_GRANT_PROVIDER_ID_PK PRIMARY KEY,
NAME VARCHAR2(255) , 
PHONE_NUMBER VARCHAR2(255),
EMAIL VARCHAR2(255),
GRANT_AMOUNT  NUMBER  CHECK(GRANT_AMOUNT>0)
);

CREATE TABLE FUNDED_BY
(
FUND_ID VARCHAR2(255) NOT NULL, 
GRANT_PROVIDER_ID VARCHAR2(255) NOT NULL,
TRX_ID VARCHAR2(255) , 
AMOUNT_PAID NUMBER CHECK(AMOUNT_PAID>0), 
CONSTRAINT FUNDEDBY_FUND_ID_FK FOREIGN KEY(FUND_ID) REFERENCES FUND_REQUESTS(FUND_ID) ON DELETE CASCADE, 
CONSTRAINT FB_GRANT_PROVIDER_ID_FK FOREIGN KEY(GRANT_PROVIDER_ID) REFERENCES GRANT_PROVIDER(GRANT_PROVIDER_ID) ON DELETE CASCADE
);

CREATE TABLE NEEDS
(
FUND_ID VARCHAR2(255) NOT NULL, 
RESEARCH_ID VARCHAR2(255) NOT NULL, 
CONSTRAINT NEEDS_FUND_ID_FK FOREIGN KEY(FUND_ID) REFERENCES FUND_REQUESTS(FUND_ID) ON DELETE CASCADE, 
CONSTRAINT NEEDS_RESEARCH_ID_FK FOREIGN KEY(RESEARCH_ID) REFERENCES RESEARCH(RESEARCH_ID) ON DELETE CASCADE
);

CREATE TABLE QUESTIONS
(
QUESTION_ID VARCHAR2(255) CONSTRAINT QUESTIONS_QUESTION_ID_PK PRIMARY KEY,
ACC_ID VARCHAR2(255) NOT NULL,
CONSTRAINT QUESTIONS_ACC_ID_FK FOREIGN KEY(ACC_ID) REFERENCES USERS(ACC_ID) ON DELETE CASCADE,
QUESTION VARCHAR2(255) );

CREATE TABLE ANSWERS
(
ANSWER_ID VARCHAR2(255) CONSTRAINT ANSWERS_ANSWER_ID_PK PRIMARY KEY ,
QUESTION_ID VARCHAR2(255) NOT NULL,
ACC_ID VARCHAR2(255) NOT NULL,
CONSTRAINT ANSWERS_ACCOUNT_ID_FK FOREIGN KEY(ACC_ID) REFERENCES USERS(ACC_ID) ON DELETE CASCADE,
CONSTRAINT ANSWERS_QUESTION_ID_FK FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID) ON DELETE CASCADE,
ANSWER VARCHAR2(255) ,
UPVOTES VARCHAR2(255) ,
DOWNVOTES VARCHAR2(255)
 );

CREATE TABLE CONFERENCE
(
CONFERENCE_ID VARCHAR2(255)  CONSTRAINT CONFERENCE_CONF_ID_PK PRIMARY KEY,
WEBSITE_LINK VARCHAR2(255) ,
SUBMISSION_DATE DATE,
START_DATE DATE,
END_DATE DATE,
VENUE VARCHAR2(255) ,
STATUS VARCHAR2(255) ,
CONFERENCE_NAME VARCHAR2(255) ,
MEMBER_RATE VARCHAR2(255) ,
NON_MEMBER_RATE VARCHAR2(255) );

CREATE TABLE CAN_KEEP_TRACK_OF
(
CONFERENCE_ID VARCHAR2(255) NOT NULL,
ACC_ID VARCHAR2(255) NOT NULL,
CONSTRAINT CONFERENCE_CONFERENCE_ID_FK FOREIGN KEY(CONFERENCE_ID) REFERENCES CONFERENCE(CONFERENCE_ID) ON DELETE CASCADE,
CONSTRAINT USERS_ACC_ID_FK FOREIGN KEY(ACC_ID) REFERENCES USERS(ACC_ID) ON DELETE CASCADE
);

CREATE TABLE SPONSORS
(
CONFERENCE_ID VARCHAR2(255)  NOT NULL,
CONSTRAINT SPONSORS_CONF_ID_PK FOREIGN KEY(CONFERENCE_ID) REFERENCES CONFERENCE(CONFERENCE_ID) ON DELETE CASCADE,
SPONSOR VARCHAR2(255) 
);

CREATE TABLE DOMAIN
(
CONFERENCE_ID VARCHAR2(255)  NOT NULL,
CONSTRAINT DOMAIN_CONF_ID_PK FOREIGN KEY(CONFERENCE_ID) REFERENCES CONFERENCE(CONFERENCE_ID) ON DELETE CASCADE,
DOMAIN VARCHAR2(255)
 );